language: python
sudo: false
python:
  - '2.7'
install:
  - pip install -r requirements.txt --upgrade
script:
  - flake8 ./lxc-bootstrap/
  - flake8 ./lxc-nuke/
cache:
  directories:
    - $HOME/virtualenv/python2.7.9
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http
